python app/gan_mel_training.py
python app/gan_mel_visualize.py 
python app/gan_mel_visualize.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_visualize.py 
python app/gan_mel_training.py 
python app/gan_mel_visualize.py 
python app/gan_mel_visualize.py 
python app/gan_mel_visualize.py 
python app/gan_mel_training.py 
python app/gan_mel_visualize.py 
python app/gan_mel_training.py 
python app/gan_mel_visualize.py 
python app/gan_mel_training.py 
python app/gan_mel_visualize.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_visualize.py 
python app/gan_mel_training.py 
python app/gan_mel_visualize.py 
python app/gan_mel_training.py 
python app/gan_mel_visualize.py 
python app/mlp_classifier.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_visualize.py 
python app/gan_mel_visualize.py 
python app/mlp_classifier.py 
python app/mlp_classifier.py 
python app/mlp_baseline
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/mlp_baseline.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_visualize.py 
python app/gan_mel_visualize.py 
python app/gan_mel_visualize.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_visualize.py 
python app/mlp_classifier.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/gan_mel_visualize.py 
python app/mlp_classifier.py 
python app/mlp_classifier.py 
python app/mlp_classifier.py 
python app/mlp_classifier.py 
python app/mlp_classifier.py 
python app/gan_mel_training.py 
python app/gan_mel_training.py 
python app/mlp_baseline.py 
python app/gan_mel_training.py 
python app/gan_mel_visualize.py 
python app/gan_mel_visualize.py 
python app/mlp_classifier.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/mlp_table.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/mlp_baseline_classifier.py 
python app/mlp_baseline_classifier.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_sp
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_visualize.py 
python app/gan_mel_training_spe.py 
python app/mlp_baseline_classifier.py 
python app/mlp_baseline_classifier.py 
python app/mlp_baseline_classifier.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py 
python app/mlp_baseline_classifier.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py 
python app/mlp_baseline_classifier.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/pdf_analysis.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py 
python app/mlp_baseline_classifier.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py 
python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py 
python app/gan_mel_visualize.py && python app/mlp_classifier.py 
python app/gan_mel_visualize.py && python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py &&  python app/gan_mel_visualize.py && python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py &&  python app/gan_mel_visualize.py && python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py &&  python app/gan_mel_visualize.py && python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py &&  python app/gan_mel_visualize.py && python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py &&  python app/gan_mel_visualize.py && python app/mlp_baseline_classifier.py 
python app/gan_mel_training_spe.py &&  python app/gan_mel_visualize.py && python app/mlp_baseline_classifier.py 
